### ISSUE TITLE
Select statements not supported

### ISSUE THREAD

**Issue by kokes** [camfort/camfort#11]
Any select statements would result in a parser error. E.g.:

```
program test

integer :: i = 42

select case(i)
	case (42)
	print *, "foo"
end select

end program test
```

I get `camfort: select.f90: line 5 column 0: syntax error (from parser)`. It's actually the number one reason I cannot use camfort for much of my code, because it always stops at these.

I've just noticed the `select` keyword is commented out [in the parser](https://github.com/dorchard/language-fortran/blob/2ab73d863f4215bfed3ed594bc221fe29c4eaec5/src/Language/Fortran/Parser.y#L162) (and [so is `case`](https://github.com/dorchard/language-fortran/blob/2ab73d863f4215bfed3ed594bc221fe29c4eaec5/src/Language/Fortran/Parser.y#L90)), is there a reason for it? I've just double checked and [it is](http://www.j3-fortran.org/doc/year/10/10-007.pdf) still a part of the standard.

Thanks!

**Comment by dorchard** [comment]
Thanks Ondrej. We are aware of this shortcoming and it is going to be remedied soon with our brand new parser.

**Comment by kokes** [comment]
I figured as much, cheekily used a GH issue so that I'd be notified when it's fixed :-)

**Comment by dorchard** [comment]
Hi kokes: a quick update. We have a new parser in place for some of the features in `camfort`, so depending on which features of it you wanted to use, this example may be fine for you now. Any of the `units` or `stencils` features work fine with this now. However, we are still in the process of converting the refactoring features to our new parser. I will keep you updated as these become available of the next 1-2 months.

**Comment by dorchard** [comment]
This is now fixed. We have the new parser used throughout CamFort now, so you should be able to deal with `select`/`case` and many other things. Thanks for your comment and please let us know if you have any other troubles!

**Comment by dorchard** [comment]
Regarding `elemental`- this is not yet supported. We have started a ticket for Fortran 95 support over at our parser's project: https://github.com/camfort/fortran-src/issues/37.
We will let you know when this is done.
