### ISSUE TITLE
Merge changes from "camera" branch into master

### ISSUE THREAD

**Issue by madgen** [camfort/camfort#110]
Possibly with some tidying up first.

**Comment by dorchard** [comment]
Fixed by 299fc5486ae707a4b0f0648181a2cea2e083848e

**Comment by madgen** [comment]
@dorchard The commit you linked fixes some tests only?

**Comment by dorchard** [comment]
Whoops wrong one: fdf056ee907165ebab67eb050b0c010af1605d00
