### ISSUE TITLE
Q: Is there a way to build camfort on Windows without hmatrix/OpenBLAS?

### ISSUE THREAD

**Issue by apthorpe** [camfort/camfort#119]
`hmatrix` is effectively unbuildable on Windows due to `ghc`s reliance on it's own partial distribution of GCC (short story: `ghc` ships with a subset of GCC which doesn't include `gfortran` which is necessary for compiling OpenBLAS which is necessary for `hmatrix`).

I've given up trying to get `ghc` to build `hmatrix` so I was wondering if there was a way to use camfort without `hmatrix`. I'm running on Windows 8.1 and therefore don't have WSL available. My main goal is running a recent build of the code natively on Windows - no Docker, no WSL - I'm trying to demonstrate a native Windows toolchain for refactoring and analyzing legacy Fortran so running the code under a pseudo-unix environment doesn't help. The most recent binaries for x64 Windows appear to be for v0.904 from 2017.

**Comment by mrd** [comment]
I had a goal to remove hmatrix usage from camfort in favour of flint, but it is fairly intertwined at the moment. The data rep of hmatrix is better than just a Haskell array and there's a number of operations taking advantage of the utility features of hmatrix, even if most of the heavy lifting is now done by flint. If you want to take a crack at it you're welcome to do so but it might involve rewriting some bits of matrix manipulation or finding an equivalent library with a decent in-memory representation of large matrices.

**Comment by znmeb** [comment]
Hmmm ... looking at this again, I wonder if you can add `gfortran` to the `pacman` step and install OpenBLAS:

https://gitlab.haskell.org/ghc/ghc/-/wikis/building/preparation/windows

**Comment by znmeb** [comment]
Happy American Thanksgiving, everyone!


[ghc-install.sh.txt](https://github.com/camfort/camfort/files/5605327/ghc-install.sh.txt)

I should probably make a repo for this, or fork the `camfort` repo and add it as a directory somewhere.

**Comment by raehik** [comment]
Thanks @znmeb for your install script! I got quite close to successfully compiling the latest CamFort with a more recent GHC on Windows (though via Stack instead of Cabal), only failing at the final testing hurdle. It's erroring on CI at my fork PR https://github.com/raehik/camfort/pull/2 (reproduced on VM).

The CI run doesn't show it, but the error points to libflint, so likely a linking issue. I'm pretty stuck so shelving it for now, but would pick it up again if anyone's willing to help out!

**Comment by raehik** [comment]
@znmeb I'm trying this again and having such an awful time. I'm able to build CamFort using your install script -- but I get lots of runtime crashes inside libflint calls. Did you try running `cabal test` when you built it before? (If you no longer have the exe or build environment on hand, no worries.)

**Comment by raehik** [comment]
Never mind, I've solved it thanks to a debugging session with @dorchard ! There's more work needed to get CamFort to be passing all tests on Windows and to create a distributable, but libflint and hmatrix (and z3) are all fine.

I'm going to close this issue and create a new one that specifically tracks Windows support.

**Comment by raehik** [comment]
To answer the original issue question:

You should be able to build hmatrix in an MSYS2 environment by installing the following packages with `pacman`:

  * `mingw-w64-x86_64-openblas`
  * `mingw-w64-x86_64-gmp`

Then install GHC (and Cabal) somehow -- I don't have good advice for this, but `ghcup` works and seems to set up my `$PATH` well enough. Then you should have no problems building `hmatrix`.

CamFort still won't build unless you have libflint on your library path. I'm working on fixing support and writing a CI script/build instructions for Windows, tracked at #139 . Any general queries should go there, or make an issue for anything specific. Closing this.

**Comment by raehik** [comment]
[Here](https://github.com/camfort/camfort/wiki/Compilation-Instructions-for-Windows) is an updated wiki page for compiling CamFort on Windows. It skips building libflint, assuming that MSYS2 provides it, but my package is pending for now -- should be merged in a couple weeks.
