### ISSUE TITLE
Stop exporting camfort as a library

### ISSUE THREAD

**Issue by madgen** [camfort/camfort#12]
Analyses are too specialised and there is no standard API, so exposing parts of the project outside is misleading.

Core analyses, eg. live variable analysis, will later be moved to a common Fortran language front-end.

**Comment by madgen** [comment]
Will have to wait until haskell/cabal#3022.

**Comment by dorchard** [comment]
It is quite convenient for us to use CamFort as a library for building evaluation programs (e.g., I did this for WSSSPE).

**Comment by vimuel** [comment]
Is this still relevant or shall we close this issue?

(@madgen: the referenced pull request in `cabal` has been merged.)

**Comment by madgen** [comment]
@dorchard what are we doing about this? if they implemented it correctly, this should speed up the build as well.

**Comment by dorchard** [comment]
I don't know. We have a few other pieces of code that import Camfort as a library (I thinking mainly of the stencil analyser that we used for corpus analysis). If we stop exporting as a library then we could think about integrating the stencil analyser into Camfort- but this feels like it would add unnecessary bloat (it is not a feature we want to expose to users particularly).

**Comment by madgen** [comment]
I retract my proposal.
