### ISSUE TITLE
Support GHC 9.0

### ISSUE THREAD

**Issue by raehik** [camfort/camfort#130]
I've got CamFort building on GHC 9.0, but it requires an updated singletons library, which makes breaking changes I don't think I can fix with cheeky CPP pragmas and internal mirror modules. Specifically, the library is now split into 3, and we use parts from all 3.

If we want to upgrade to GHC 9.0, I see two options:

  * Stop supporting old GHCs
  * Only use the core library, and write out all TH and prelude usages manually (unsure how much work this might be)

**Comment by raehik** [comment]
The code generated by TH is complex enough (specifically in Language.Fortran.Model.Singletons) that it turns me off from trying the manual approach for now. So, this is on pause until it matters to someone else -- as much as I'm update-prone, I don't like the idea of dropping GHC 8.8/8.10 support.

**Comment by raehik** [comment]
See !131 for some more notes.

**Comment by dorchard** [comment]
Can we close this one now?

**Comment by raehik** [comment]
Resolved by #155 (by dropping support for GHC 8.10 and below).
