### ISSUE TITLE
When I use camfort's common elimination for Fortran77 legacy, I get an error.

### ISSUE THREAD

**Issue by 0xzhang** [camfort/camfort#134]
```shell
toor@HOME {~/camfort-bundle-1.0} $ ./camfort common -F 77legacy 1.f 11.f
```
```shell
Refactoring common blocks in '1.f'
Successfully parsed 0 summary file(s).
Finished running common block refactoring on input '<unknown>' ...
Logs:

Result... OK:

Writing 11.f
camfort-bin: Trying to compare differently named common blocks: Just "machin" and Just "system"

CallStack (from HasCallStack):
  error, called at src/Camfort/Transformation/CommonBlockElim.hs:423:10 in camfort-1.0-DJOQVydlyigIv03xNhT79w:Camfort.Transformation.CommonBlockElim
```

**Comment by raehik** [comment]
Thanks for the issue. Would you be able to provide any source code, or a minimal snippet that produces the behaviour? I can't glean anything from the error message immediately without the associated Fortran. The neighbouring functions returning runtime errors indicates to me that this is an unexpected codepath, so I'm wondering if it's a bug in the refactoring, or a problematic source file.

**Comment by 0xzhang** [comment]
@raehik Thanks for your reply. Could I send the source code file to your email? The code can be compiled by gfortran. I'm refactoring many Fortran77 legacy files. I don't know why occur this error and I really hope use camfort automatic eliminate common blocks.

**Comment by dorchard** [comment]
Thanks for that. We are looking into this. It looks like a bug on our end.
