### ISSUE TITLE
Windows install of 1.1.1 - "The code execution cannot proceed because libbas.dll was not found"

### ISSUE THREAD

**Issue by lewist57** [camfort/camfort#149]
Installing Windows binary for 1.1.1 on Windows 10 produces this system error:

"The code execution cannot proceed because libbas.dll was not found. Reinstalling the program may fix this probelm."

**Comment by dorchard** [comment]
Hmm! Sorry about this. Strangely I cannot find what libbas.dll is online... is there any chance it is actually libblas.dll that is missing (as in something coming from a dependency on BLAS)?

**Comment by raehik** [comment]
Hi @lewist57 . I assume it's `libblas.dll` that's missing. Did you download CamFort from the [Releases](https://github.com/camfort/camfort/releases) page? Make sure for 1.1.1, you grab the one named `camfort-windows-distrib-manual.zip`, or for 1.1.2 download the one starting `camfort-bundle-windows`.

We provide the plain executable for systems that already have dependencies installed, but handling libraries is a pain on Windows, so those releases bundle the required DLLs. Both include `libblas.dll`. You have to run the executable in the same directory with all the `lib*.dll` files, moving it will mean Windows can't find them (and might give you that message).

**Comment by lewist57** [comment]
OK, the first issue was that I was trying to run the wrong version, 1.1.2.  

I have subsequently downloaded the camfort-windows-distrib-manual.zip for 1.1.1. The .exe and all of the dlls are in the same folder on the Desktop.  Windows 10 balked at the installation the first time, but I told it to run anyway.  It seems to run at least a CMD window for 1 second, and then nothing happens.  Is it possible that one or more anti-virus programs are preventing it from starting? I am using Malwarebytes and added the .exe to the exclusion list, but no difference..............just a CMD window pops up briefly then shuts down and no program startup. Also tried running compatibility troubleshooting, no difference. Scanned file with Windows Defender, did not report any threats.

**Comment by raehik** [comment]
OK, great. Windows doesn't make using non-graphical programs easy, you do have to open a command window in the unzipped CamFort directory (or it can't find the executable you want to run). Didn't know Powershell had that behaviour, but glad to know it works.

CamFort is a command-line program that can run various analyses by passing it different arguments, and telling it where source files are to inspect. e.g. if you want to use the units of measure checking feature, take a look at [Wiki: Units of Measure](https://github.com/camfort/camfort/wiki/Units-of-Measure). You could try

    camfort units-suggest <src dir/file>

in a Powershell or `cmd.exe` window. CamFort should run, and you should get a report in the command window. The rest of the [wiki](https://github.com/camfort/camfort/wiki) has more notes on other tools available.

Thanks for these notes, we do want a better experience for using on Windows. Wonder if there's a simple GUI builder we can bolt on top.

**Comment by lewist57** [comment]
Invoking a Powershell in the folder results in the same error message, unfortunately.

As far as a GUI goes, one could create a Windows program that uses either Windows Form or WPF form in either VB or C#, collect the user input on options, but then the question is passing the user input to your program.  You could use standard tools to display the text files (original code v. refactored code), print, etc.

I am a retired Mechanical Engineer with decades of "exposure" to both Fortran (up through 77) and Visual Basic, but my skill sets are non existent when it comes to the 21st century languages like C#, Haskell and Python.  I am investigating the possibility of developing my own programs to upgrade and (partially) refactor old engineering code from 66/77 into either 95 or 2003 standards, and came across information on CAMFORT, and thought it would be interesting to see how it does refactoring and other program upgrades.

Just for fun (and for free), would you be interested if I developed an example Windows GUI program (not functional) and send the installation file(s) for your consideration?  It would be in VB, but I assume someone in your department could easily port it over to C#, just to see if your team might be interested in implementing your own GUI front end?  I may be able to throw something together by next week and ship next week, if you would be interested. Otherwise, your team could probably do a better job than me.

Thanks for your help so far.

**Comment by raehik** [comment]
> Invoking a Powershell in the folder results in the same error message, unfortunately.

Ah, I see what you mean. Running `camfort.exe` with no flags or options simply prints a version string and exits. There's help built-in to the executable, but it doesn't tell you how to get it. That's bad, I'll see about changing the behaviour there.

Try running `.\camfort.exe --help` in Powershell or cmd.exe. You should get a list of commands. Each command has its own further arguments - for those, see e.g. `.\camfort.exe units-suggest --help` (with the `--help` coming after the command). Two commands that will probably give you some feedback:

    camfort units-suggest <Fortran file>
    camfort units-infer <Fortran file>

The wiki has explanations on what things do/how to use them. If you can get it working, I think it'd be best to play around and see if CamFort can tell you anything potentially useful about your code.

> I am investigating the possibility of developing my own programs to upgrade and (partially) refactor old engineering code from 66/77 into either 95 or 2003 standards

You might also be interested in Wim Vanderbauwhede's tool https://github.com/wimvanderbauwhede/RefactorF4Acc ! It's aimed more explicitly at automatic refactoring (CamFort does that, but also lots of separate configurable analyses) of F77 to F95, replacing the wonky features for the standardized ones.

> Just for fun (and for free), would you be interested if I developed an example Windows GUI program (not functional) and send the installation file(s) for your consideration?

The main work involved would be turning each command into a "tab" that enumerates the arguments, and writes a command line to send to the executable. It would be a decent amount of boilerplate!

Wouldn't mind at all if you wanted to write an example. I would prefer a cross-platform solution if possible, but I don't know if there's any good existing framework out there (found nothing appropriate on a quick google).

**Comment by lewist57** [comment]
Thank you very much for your kind response.  Yes I have seen RefactorF4Acc on Github but have not had much time to study it.

Regarding your last comments:

_The main work involved would be turning each command into a "tab" that enumerates the arguments, and writes a command line to send to the executable. It would be a decent amount of boilerplate!_
It might not be as hard as it would seem, let me see if I can produce a non-functioning GUI as an "inspiration" to what you may want to create for a front end.

_Wouldn't mind at all if you wanted to write an example. I would prefer a cross-platform solution if possible, but I don't know if there's any good existing framework out there (found nothing appropriate on a quick google)._  Unfortunately I can't help there. Some of my other programs, such as Davinci Resolve apparently has done a great job of creating the same GUI for the program on Windows, Linux and Mac.  My skill sets are limited to Windows only, but there might be a cross platform GUI add on out there somewhere.

**Comment by lewist57** [comment]
I am getting there, many thanks for your tolerance.  So I have camfort.exe, the associated DLLs and a fortran program, charnum.for all in the same folder, and have been trying out the program.

Typing in .\camfort.exe -help does produce the help listing.  As a test, I tried typing in the following line of code in the PowerShell window (invoked within the folder with the files):

.\camfort.exe common charnum.for

and get the following response:

PS C:\Users\lewis\Desktop\camfort> .\camfort.exe common CHARNUM.FOR
Missing: (FILENAME | --inplace)

Usage: camfort.exe common FILENAME [-I|--include-dir DIR] [-e|--exclude FILE...]
                          [-F|--fortranVersion VERSION] [--debug] [--snippets]
                          (FILENAME | --inplace)
  common block elimination

So obviously I am doing something wrong in trying to tell CAMFORT the input fortran filename to be processed.  Once again, I am an engineer, and not a computer science major, so my apologies for the lack of understanding on my end.

On a "Windows" front end program, it will not be that hard to have a standalone windows program to gather user input/options and invoke via PowerShell command window. BUT I would prefer to better understand the existing command line interface and options before I proceed with the development of the example program.

**Comment by raehik** [comment]
`camfort.exe common --help` displays the following:

```
Usage: camfort common FILENAME [-I|--include-dir DIR] [-e|--exclude FILE...] 
                      [-F|--fortranVersion VERSION] [--debug] [--snippets] 
                      (FILENAME | --inplace)
  common block elimination

Available options:
  FILENAME                 input file
  ...
  --inplace                write in place (replaces input files)
  FILENAME                 file to write output to
```

So you need to provide either 2 files (input, output), or 1 file and the `--inplace` flag to make changes directly to the input file. This is what the error message is telling you: you needed one of `FILENAME` or `--inplace` to run the command. I suggest writing to a new file e.g. `camfort.exe common CHARNUM.FOR CHARNUM_CMN_ELIM.FOR`.

I realize the help dialogs can be a bit overwhelming, `common` has more options you probably don't need. The wiki has walk-through examples for some commands. I'll make a note to insert example invocations for each command in their help dialog.

**Comment by lewist57** [comment]
Thank you again for your input in explaining the format of the command string.

Unfortunately, in using .\camfort.exe common <input filename.for> <oiutput filename.for> consistently generates the error message "lexing failed", as per below:

PS C:\Users\Tony Lewis\Desktop\camfort\camfort-distrib-manual> .\camfort.exe common sales.for newsales.for
Refactoring common blocks in 'sales.for'
Successfully parsed 0 summary file(s).
sales.for, 6:1: sales.for: lexing failed.
Last parsed token: TNewline (5:17)-(5:17).
Finished running common block refactoring on input '<unknown>' ...
Logs:

Result... OK:

and no output file is generated. I tried the same command on 3 - 4 various Fortran 77 source codes, but always get the "lexing failed" error message.

I *assume* that CAMFORT will accept a standard *.TXT input file, as per DOS/WINDOWS. It has been my experience that a lot of old code has problems such as embedded TABs, and what appear to be blank lines are actually empty lines with no white space at all, as well as misalignment of the labels, continuation symbols and code with the standard F77 format, so I don't know if this is potentially causing a problem with CAMFORT.

For example, I am getting the "lexing failed" error with this simple program:

   PROGRAM MAIN
	CALL DISPLY
	STOP
	END
*
      SUBROUTINE DISPLY
	WRITE(6,*) 'HELLO THERE WORLD!'
	RETURN
	END

And changing the options  from common to equivalence or dead also results in the 'lexing failed" error message.  Ideas?

**Comment by raehik** [comment]
@lewist57 Could we swap to email for troubleshooting? No rudeness, just to keep on-topic. I can't see an address on your account, so if you could email me at the address on my profile we can talk there & I can close this issue. For now though:

Yes, parsing Fortran is irritating. For that simple file, the culprit is the sole `*`. Remove it and it should parse. (I've not seen that syntax before, is it maybe how separate cards were read into a digital file?)

**Comment by lewist57** [comment]
No problem, sent email to your gmail account with my email address.

"parsing Fortran is irritating".  No, parsing Fortran is impossible, but the best we can do is try!

Thanks again for your help.
