### ISSUE TITLE
README outdated?

### ISSUE THREAD

**Issue by zbeekman** [camfort/camfort#15]
It appears that comfort and the language-fortran parser have been moved into the camfort org from @dorchard's personal account, is this true? If so the README needs updating... I could submit a quick PR if that's the case.

**Comment by madgen** [comment]
Yup, that's true and you're very welcome! Many thanks in advance.

**Comment by dorchard** [comment]
Thanks. Though `language-fortran` is still under my account. We are switching to the new parser `fotran-src` soon, but the `master` branch of `camfort` still uses `language-fortran` (though it is also available on Hackage).

**Comment by zbeekman** [comment]
oh, ok... so for now `dorchard/language-fortran` is correct, but `fortran-src` will become the new parser sometime in the future?

Also, have you heard of Craig Rasmussen's Open Fortran Parser project? I don't know how extensive your parser is in its ability to handle all of Fortran's language features, but Craig's OFP currently uses Strategoxt which is unmaintained (although stewardship has been transferred over to him, more or less) and is currently only installable from years old pre-compiled binaries on most systems... Your actively maintained, haskell based parse seems like it could be a saner starting point, although I don't know how much work he would have to do to reinvent the wheel...

Over at https://github.com/sourceryinstitute/opencoarrays we're in the process of creating a source to source translation tool to allow older GFortran compilers ( < 5.1 ) as well as other compilers  with no/poor coarray Fortran capabilities to be able to support most of the F2008 and F2015  CAF language features.  The transpiler reads source code with CAF syntax and creates intermediate sources that call into the OpenCoarrays library (the main portion of which sits on top of an MPI-3 implementation, however there is some experimental support for GASNet). We're working with Craig and OFP to achieve this, but if you can generate ASTs for modern Fortran (with coarray syntax) your actively maintained Haskel could be a better alternative... I'd be curious to hear your thoughts on the matter, and might put you in touch, if you'd be open to the idea...

**Comment by madgen** [comment]
@zbeekman with regards to how much work: the answer is 8 months worth of man hour for Fortran 66, 77, and 90. Give or take... with plenty of bugs.

**Comment by zbeekman** [comment]
Does that mean that the status of support for >= F2003 is minimal/non-existant?

**Comment by madgen** [comment]
At this moment it is non-existant but that's only because we started from 66 standard and are moving our way up the ladder. We are just trying to finish off 90 and then want to move to 95, 2003, 2008, and eventually 2015 (probably when it gets standardised).

**Comment by zbeekman** [comment]
@madgen Thanks so much for the info! 

As a corollary, does that mean camfort won't be able to deal with (for it's units analysis) Fortran sources with Fortran 2003 syntax?

It sounds like right now we'll have to stick with crusty StrategoXT, but may be able to re-evaluate `fortran-src`/`camfort` in the future. Maybe I'll have to learn Haskell, so I can help 😉 (unlikely at this point in time, however)

**Comment by madgen** [comment]
@zbeekman Indeed, it won't be able to deal with Fortran 2003 for a while as CamFort will entirely depend on fortran-src's capabilities.

You should give it a go! Haskell is a wonderful language.

If you'd like to help you can try to try source code for 66/77/90 with fortran-src (you don't need to learn Haskell as it has a command line utility that dumps a parse tree) and open issues for failing standard compliant files. I will write a README for it today or tomorrow for the command line tool. Hopefully, that should help.
