### ISSUE TITLE
Releases & Homebrew/Linuxbrew

### ISSUE THREAD

**Issue by zbeekman** [camfort/camfort#16]
Once you start publishing releases, and if the project  grows enough to pass the "popularity contest metric" (Homebrew calls it notability) I'd be happy to work on submitting a Homebrew formula.

(In the mean time encourage people to star, watch and fork comfort and language-fortran...)

**Comment by madgen** [comment]
You can now download via our tap for Homebrew using `brew install camfort/camfort/camfort`. It has bottles too, so it should take much faster than compilation.

For further instructions/other installation methods checkout [the installation guide](https://github.com/camfort/camfort/wiki/Installation-Guide).
