### ISSUE TITLE
All file/line/column notations should be in standard notation so IDEs can hook into it

### ISSUE THREAD

**Issue by dorchard** [camfort/camfort#177]

**Comment by dorchard** [comment]
Should be `filename:line:col`

**Comment by dorchard** [comment]
I've made a PR doing this for units-suggest, but now I'm wondering whether we should do this for `units-infer` too, which uses yet a different format:
```
% camfort units-infer do-loop1.f90 
Inferring units for 'do-loop1.f90'
Successfully parsed 0 summary file(s).
Finished running unit inference on input 'do-loop1.f90' ...
Logs:

Result... OK:

do-loop1.f90:
  3:11 unit m :: x
  3:14 unit m :: y
  4:14 unit m :: i
  10:3 unit 1 :: f
  11:13 unit 1 :: x
  11:16 unit 1 :: y
  12:16 unit 1 :: i
```

**Comment by jaytorry** [comment]
Yes I think it would be useful to apply this to _units-infer_, _units-synth_ and _units-check_ (in that order of priority?). 

I have also opened an issue regarding the _order_ of units-suggest outputs (#201).

**Comment by dorchard** [comment]
This is fixed by: https://github.com/camfort/camfort/pull/197
