### ISSUE TITLE
units-suggest ignores uninitialised variables

### ISSUE THREAD

**Issue by jaytorry** [camfort/camfort#187]
_units-suggest_ appears to ignore variables which are declared, but not initialised, in the input file. 

Uninitialised variables are sometimes suggested when _units-suggest_ is called higher in the dependency tree (i.e. if a variable is declared in _file A_ and initialised/used in _file B_). However, some users may wish to _fully_ specify each file before moving on. 

Perhaps there could be an additional option for units-suggest ("_--include-all_", or similar)?

```
module unused_modvar

    implicit none

    real :: not_initialised

    real :: initialised = 5.0

end module
```

```
$ camfort units-suggest unused-modvar.f90 -l 'poly'
Suggesting variables to annotate with unit specifications in 'unused-modvar.f90'
Successfully parsed 0 summary file(s).
Finished running unit critical variable analysis on input 'unused-modvar.f90' ...
Logs:

Result... OK:

unused-modvar.f90: 1 variable declarations suggested to be given a specification:
    unused-modvar.f90 (8:13)    initialised

```

**Comment by dorchard** [comment]
Fixed by https://github.com/camfort/camfort/pull/206
