### ISSUE TITLE
Wrong inference result on region product

### ISSUE THREAD

**Issue by madgen** [camfort/camfort#19]
``` fortran
program failing
  integer, dimension(10,10) :: a
  integer :: i, j

  do i = 1, 10
    do j = 1, 10
      a(i,j) = a(i  ,j) + a(i  ,j+1) + a(i  ,j+2) &
             + a(i+1,j) + a(i+1,j+1) + a(i+1,j+2) + a(i,1)
    end do
  end do
end program failing
```

`a` above gets a stencil of `stencil readOnce, (forward(depth=1, dim=1))*(forward(depth=2, dim=2)) :: a`.
We describe `*` as a stencil of bounded box, but we can't guarantee a(i,1) will always be in the box.

Note that if the assignment is changed to

``` fortran
      a(i,j) = a(i  ,j) + a(i  ,j+1) + a(i  ,j+2) &
             + a(i+1,j) + a(i,1)
```

We correctly infer `stencil readOnce, (forward(depth=1, dim=1)) + (forward(depth=2, dim=2)) :: a`. This is correct with respect to our description because we describe `+` operator as conjunction of both specifications and `a(i,1)` is a legit access pattern for the former stencil spec.

**Comment by dorchard** [comment]
Interesting. Do you think that we should reject the first piece of code? Or infer a difference stencil? At the moment we allow constants to appear in dimension positions where elsewhere they are neighbourhood indices and `inconsistentIVs` does not disallow this: which I think is reasonable, but there are two possibilities which would provide stronger guarantees/more information: 
disallow it (which means we either accept less code, or perhaps use a bound in the above case), or come up with some way to represent this case with a different spec (not so preferable as we have to revisit the design).

**Comment by madgen** [comment]
We should be infering a `+` spec rather than a `*` spec because the latter semantically means simultaneous constraint on indexing behaviour and here `a(i,1)` clearly violates that constraint. Same spec with `+` instead of `*` would be consistent with what `+` means which is the the stencil is consistent with either the left operand (in this case acting on dimension 1) or right operand (dimension 2).

**Comment by dorchard** [comment]
So you suggest the correct specification here should be :
```
stencil readOnce, (forward(depth=1, dim=1)) + (forward(depth=2, dim=2)) :: a
```
I can see how that makes sense with the meaning of `+`. But should `+` mean consistent with the left and the right?

**Comment by dorchard** [comment]
We have completely change the meaning of the specifications when constants are involved in dimensions- so this is not longer a valid discussion.

For reference, the new version gives:
```
      != stencil readOnce, (pointed(dim=1)) + (forward(depth=1, dim=1))*(pointed(dim=2)) :: a
      a(i,j) = a(i  ,j) + a(i  ,j+1) + a(i  ,j+2) &
             + a(i+1,j) + a(i,1)
      != stencil readOnce, (pointed(dim=1)) + (forward(depth=1, dim=1))*(forward(depth=2, dim=2)) :: a
      a(i,j) = a(i  ,j) + a(i  ,j+1) + a(i  ,j+2) &
             + a(i+1,j) + a(i+1,j+1) + a(i+1,j+2) + a(i,1)
```
