### ISSUE TITLE
Inference failure

### ISSUE THREAD

**Issue by madgen** [camfort/camfort#20]
```fortran
program failing
  integer, dimension(10,10) :: a
  integer :: i, j

  do i = 1, 10
    do j = 1, 10
      a(i,j) = a(i  ,j) + a(i  ,j+1) + a(i  ,j+2) &
             + a(i+1,j) + a(i+1,j+1) + a(i+1,j+2) + a(i+1,1)
    end do
  end do
end program failing
```

Snipper above fails on inference with `src/Camfort/Analysis/StencilSpecification/Syntax.hs:(232,1)-(243,25): Non-exhaustive patterns in function equalModuloFwdBwd`.

Note the error occurs with the addition of final term `a(i+1,1)` and it doesn't occur if the term has already been observed such as `a(i+1,j)`. It also doesn't occur with `a(i,1)`.

The same error is not limited to terms with absolute indices `a(i+1,j+3)` also fails. rather than creating a bounded spec.

**Comment by madgen** [comment]
So basically, equalModuloFwdBwd is called with two lists of regions of unequal length. Where are dependent types when you need them, amirite?

**Comment by dorchard** [comment]
This appears to not be a problem anymore. CamFort infers:
```
failing.f90
((7,7),(8,60)) 	stencil readOnce, (forward(depth=1, dim=1, irreflexive)) + (forward(depth=1, dim=1))*(forward(depth=2, dim=2)) :: a
```
`equalModuloFwdBwd` got some rewrites as part of the front-end simplifier so I guess that fixed it.
