### ISSUE TITLE
`units-infer` doesn't stop at inconsistency

### ISSUE THREAD

**Issue by dorchard** [camfort/camfort#26]
(branch: units-new) 
For example:
```
program main
  != unit(A) :: x
  real :: x
  != unit(B) :: y
  real :: y
  x = inc(x)
  y = inc(y)
end program main

real function inc(x) 
    real x  
    inc = x + 1
end function
```
`units-check` rightfully calls this inconsistent but `units-infer` makes both `x` and `y` have units `b`.

**Comment by mrd** [comment]
units-infer will now check that the program is consistent before issuing recommendations :)
