### ISSUE TITLE
Example where units-infer doesn't give a unit where it should (multi-variate polymorphism)

### ISSUE THREAD

**Issue by dorchard** [camfort/camfort#27]
```
program main
  != unit(A) :: x
  real :: x
  != unit(B) :: y
  real :: y
  real :: z
  z = mult(x,y) + mult(y,x)
end program main

real function mult(x,y)
    real x
    real y
    mult = x * y
end function
```
gives
```
poly-example2.f90: ((3,11):(3,11) - (3,11):(3,11)) unit a :: x
poly-example2.f90: ((5,11):(5,11) - (5,11):(5,11)) unit b :: y
```
but it should also have `unit (a b) :: z`. Possibly this is that equality on units isn't taking into account commutativity?

**Comment by mrd** [comment]
No, the equality is all handled through matrices, as the paper lays out.

The problem is that I was only giving a constraint between the units of the addition operands, but not actually assigning a unit to the result of the addition operation.

Easy fix.
