### ISSUE TITLE
Incorrect normalisation of units

### ISSUE THREAD

**Issue by madgen** [camfort/camfort#28]
```fortran
program normal_form
  != unit u1 / (u2 / u3) :: x
  integer x

  != unit u1 / (u2 * u3) :: y
  integer y = 10

  x = y
end program normal_form
```

This is interpreted as consistent under `units-check` on new-units branch (CC @mrd). But it throws an error on master.

I think both behaviours are wrong.

**Comment by dorchard** [comment]
This bug remains.

**Comment by mrd** [comment]
This is not to do with normalisation but rather to do with parsing.

The new units parser does not lex or parse the '*' operator.

**Comment by mrd** [comment]
Duplicate of #30.
