### ISSUE TITLE
cabal install camfort fails

### ISSUE THREAD

**Issue by ZedThree** [camfort/camfort#33]
Hi, I just tried to install camfort-0.802 via cabal, and it failed here:

```
...
[25 of 42] Compiling Camfort.Transformation.CommonBlockElim ( src/Camfort/Transformation/CommonBlockElim.hs, dist/build/Camfort/Transformation/CommonBlockElim.o )

src/Camfort/Transformation/CommonBlockElim.hs:292:31:
    No instance for (Monad ((,) Report)) arising from a use of ‘foldM’
    In the expression:
      foldM
        (\ p (c1, c2)
           -> (coherentCommonsP c1 c2) >>= (\ p' -> return $ p && p'))
        True
        (pairs commons)
    In an equation for ‘allCoherentCommonsP’:
        allCoherentCommonsP commons
          = foldM
              (\ p (c1, c2)
                 -> (coherentCommonsP c1 c2) >>= (\ p' -> return $ p && p'))
              True
              (pairs commons)
Failed to install camfort-0.802
cabal: Error: some packages failed to install:
camfort-0.802 failed during the building phase. The exception was:
ExitFailure 1
```

I'm using OpenSUSE 13.2 and 
```
$ cabal --version
cabal-install version 1.22.9.0
using version 1.22.8.0 of the Cabal library 
```

**Comment by madgen** [comment]
Sorry, this is our bad that we didn't put a lower bound on GHC's Base package.

We will make a release that includes a fix to that but meanwhile if you upgrade to GHC 8, the problem will go away.

**Comment by ZedThree** [comment]
Thanks for the quick response! Unfortunately, it looks like GHC 8 isn't available yet for my distro.

**Comment by madgen** [comment]
Hmm, I will look into making it compatible.

Meanwhile there is a (dynamically linked) binary for the older version (I will update that to an up to date version today as well) in the [installation guide](https://github.com/camfort/camfort/wiki/Installation-Guide). It should work if you can get the dependencies for your distro. Let me know if you are having any difficulties with that.

**Comment by ZedThree** [comment]
Thanks, I didn't spot that. The binary runs, but I get "syntax error (from parser)" on most files. It choked on a F77-style comment line ("C" in first column), on the new line in a derived type declaration:
```
TYPE Map
  ...
```
in an F90 file, and on pointer assignment:
```
field_aux(0:nx,0:ny,k_low-1:k_high+1) => workf(:,:,:,1)
```

Any ideas?

**Comment by dorchard** [comment]
Hi @ZedThree, which feature of Camfort are you trying to use? We actually have two different parsers being used internally, one which is much more robust than the other! We are in the process of converting everything to use the better parser.

**Comment by ZedThree** [comment]
Sorry, that was with `count`, `loops` and `common`:
```
$ camfort common annotp.f cam_output
CamFort 0.776 - Cambridge Fortran Infrastructure.
Refactoring common blocks in "annotp.f"

annotp.f
camfort: annotp.f: line 2 column 1: syntax error (from parser)

$ head -2 annotp.f
      SUBROUTINE ANNOTP(IDIRX,IDIRY)
C
```


`ast` gives me a different error:
```
$ camfort ast annotp.f cam_output
CamFort 0.776 - Cambridge Fortran Infrastructure.
annotp.f/cam_output
camfort: annotp.f/cam_output: openFile: inappropriate type (Not a directory)
```

**Comment by madgen** [comment]
Not much we can do for the parser issues right now as some analysis use the old and very fragile parser. Hopefully, they will be updated soon.

As for the verification commands related to units and stencils, they should be able to deal with most Fortran programs and certainly in the presence of 77 comments, etc.

I have made a new version but it will take a while to get it into Hackage (cabal's package database), as soon as I upload the dynamically linked binary, I will let you know here. Until then I am retaining the issue open.

Also thanks a lot for reporting these. It really helps. Please do let us know if you come up with more ways to break it!

**Comment by dorchard** [comment]
Incidentally `loops` was deprecated and I just removed it, and I just updated `count` to work with the new parser. But `common` won't be fixed for a couple of weeks.

**Comment by madgen** [comment]
@ZedThree: Hey again! We have made a new release and here's an updated [Linux binary](https://github.com/camfort/camfort/releases/download/v0.804/camfort-Linux-x64.tar.gz).

I'm afraid you'll still have to wait until refactoring routines switch to the new parser.

Let me know if your problems persist.
