### ISSUE TITLE
Support doxygen notation for specifications

### ISSUE THREAD

**Issue by dorchard** [camfort/camfort#35]
Doxygen picks up comments of the form `!<` so it won't pick up any specifications in CamFort which start `!=`. We could easily allow `!<` or `!<=` to be used in CamFort (could be a command line option for synthesis commands to tell CamFort which prefix to generate) so that units/stencils/etc. can get into doxygen?

**Comment by zbeekman** [comment]
Please also consider [FORD](https://github.com/cmacmackin/ford) documentation... can be made mostly compatible with DOXYGen

**Comment by dorchard** [comment]
Thanks! Will do.

**Comment by dorchard** [comment]
From the FORD documentation:
```
In modern (post 1990) Fortran, comments are indicated by an exclamation mark (!). FORD will ignore a normal comment like this. However, comments with two exclamation marks (!!) are interpreted as documentation and will be captured for inclusion in the output. 
```

**Comment by dorchard** [comment]
I propose we add a flags `--doxygen` and `--ford` (mututally exclusive) which for `units-synth` and `stencil-synth` generate either `!<` or `!!` respectively for specification lines and I propose that we just recognise both by default in the comment annotator parser?

**Comment by zbeekman** [comment]
Just FYI, FORD can be [configured](https://github.com/cmacmackin/ford/wiki/Project-File-Options#docmark) to use !< as well... so you may not even need to create a separate treatment for FORD...

**Comment by dorchard** [comment]
Ah, good to know. Thanks!

**Comment by madgen** [comment]
So do we need '<' as well?
