### ISSUE TITLE
Replace use of tabs in CamFort output with a smarter mechanism for column alignment

### ISSUE THREAD

**Issue by dorchard** [camfort/camfort#38]
Currently tabs are used in various places which lead to poorly formatted outputs.

**Comment by hholst80** [comment]
Tabs? Thats not even valid Fortran code. Are they removed in a post step?

**Comment by dorchard** [comment]
Apologies, I was not clear. Tabs are only used for the reports produced by CamFort on the command line, not in any generated Fortran code.
