### ISSUE TITLE
Synthesis only generates Fortran 90 style comments

### ISSUE THREAD

**Issue by madgen** [camfort/camfort#39]
Synthesis for both stencils and units generate Fortran90 style comments.

**Comment by dorchard** [comment]
I've made a separate fixture to show what should happen, and reverted the test for now to accommodate this inaccuracy so that our build will work.

**Comment by madgen** [comment]
[Bugs should fail builds.](http://martinfowler.com/articles/continuousIntegration.html)

**Comment by dorchard** [comment]
I would like Travis to generate binaries for us as I need to do a new release to fix Stackage. I don't have time to fix this bug, but we need to fix Stackage ASAP.

**Comment by madgen** [comment]
Fair

**Comment by madgen** [comment]
@dorchard do we want to ship with this bug?

**Comment by vimuel** [comment]
I can't reproduce this.

`$ camfort units-synth samples/units/stuck1.f --inplace`

on the file

```fortran
      PROGRAM ONE
        IMPLICIT NONE
        REAL  radius, height
        REAL  mass
        REAL  densit, volume, pi, i
        volume = pi * radius**2 * height
        mass = volume * densit

        do 10 i=1,10
           radius = i
 10     continue
      end
      function r(m,t,a)
        integer m,a(10)
        real t

        r = 0.1*t * (m**2 + 14*m + 46)
        if (r .LT. 0) r = 0.0

        return
      end
```

is giving the following output:

```fortran
      PROGRAM ONE
        IMPLICIT NONE
        REAL  radius, height
        REAL  mass
        REAL  densit, volume, pi, i
        volume = pi * radius**2 * height
        mass = volume * densit

        do 10 i=1,10
           radius = i
 10     continue
      end
c= unit('a) :: r
      function r(m,t,a)
c= unit('b) :: a
c= unit(1) :: m
        integer m,a(10)
c= unit('a) :: t
        real t

        r = 0.1*t * (m**2 + 14*m + 46)
        if (r .LT. 0) r = 0.0

        return
      end
```

**Comment by dorchard** [comment]
`units-synth` might be doing things correctly. How about `stencils-synth`?

**Comment by vimuel** [comment]
My bad.

**Comment by dorchard** [comment]
Not at all, I think when the bug was first posted `units-synth` was wrong as well (hence the bug report from @madgen says "stencils and units").

**Comment by vimuel** [comment]
Can confirm that this is still an issue with `units-synth`.

**Comment by mrd** [comment]
Thought I fixed it recently by passing the meta info thru the synth
functions.

**Comment by dorchard** [comment]
You did @mrd - I think the problem is just with `stencils-synth` now.
