### ISSUE TITLE
Deprecating several functions from Renaming module

### ISSUE THREAD

**Issue by mrd** [camfort/camfort#42]
`extractNameMap`, `renameAndStrip`, `underRenaming`, and the type `NameMap` will not be available once we support module use-renaming, therefore they should be phased out.

I have already removed them from the units-of-measure modules.

**Comment by dorchard** [comment]
I have removed these from the stencil-specs in ad89573c69416bb1bf285f56de37430c23c84eaa
Can we close this issue now?
