### ISSUE TITLE
Better documentation, especially the physical units capability

### ISSUE THREAD

**Issue by zbeekman** [camfort/camfort#5]
Hi,
I’m very interested in your Fortran refactoring tool, and would love to know more about it. I’ve read the paper and poster posted at http://www.cl.cam.ac.uk/~dao29/camfort/ and understand that this is software is under development, but it looks as though it has the potential to be extremely useful and powerful—even in its current state. Furthermore, I am intrigued by what appears to be consistency checking/validation of physical units. This feature in particular is lacking documentation. I understand that you are probably quite busy, as am I, but a small amount of effort invested in documentation could go a long way, and encourage early adoption of your tool. :+1:

**Comment by zbeekman** [comment]
Hi Dominic,
Just wondering if there are any references that you can me too for more information, since you responded to my last inquiry. The units stuff still interests me, especially if they can be specified as comments, and the other analysis and transformations look quite useful, but I have no idea where to begin.

Thanks!

**Comment by zbeekman** [comment]
ping @dorchard

**Comment by dorchard** [comment]
Hi!
We are doing a large amount of work overhauling almost everything to do with the parser at the moment. Units are now specified via comments and we are working on some other specifications. The paper I mentioned before is here: http://www.cl.cam.ac.uk/~acr31/pubs/contrastin-units.pdf
If you take a look at the `HEAD` branch this should match what is in this article and shows how the comments system can be used. 

We will be  pushing a brand new version of the tool in July with various things update and new features.

**Comment by zbeekman** [comment]
@dorchard Thanks so much for getting back to me, I appreciate it!

**Comment by dorchard** [comment]
No problem. Let us know if we can help. Best, Dominic

**Comment by madgen** [comment]
Here's up to date [documentation for units-of-measure verification](https://github.com/camfort/camfort/wiki/Units-of-Measure).

If you are interested there is also a page on stencil computation verification in the wiki!
