### ISSUE TITLE
Inferring empty atLeast approximation

### ISSUE THREAD

**Issue by madgen** [camfort/camfort#52]
```fortran
program approximate
  integer, dimension(10) :: a
  integer :: i

  do i = 1, 6
    a(i) = a(i+4)
  end do
end program approximate
```
`stencils-infer` gives us this:

```
Infering stencil specs for 'approximate.f90'

approximate.f90
(6:5)-(6:17)    stencil atLeast, readOnce,  :: a
(6:5)-(6:17)    stencil atMost, readOnce, (forward(depth=4, dim=1)) :: a
```

**Comment by madgen** [comment]
I think this is a bug we introduced along the way.

**Comment by dorchard** [comment]
I noticed this a few weeks ago and fixed it but seem to not have pushed it yet. I will get to this shortly.

**Comment by dorchard** [comment]
Fixed by commit 10b942487e69e91ceabf27ba926751e456c653c7

**Comment by madgen** [comment]
Why are we emitting an empty lower bound?

**Comment by dorchard** [comment]
Yeah, we don't really need to. Should be fairly easy to filter this out.
