### ISSUE TITLE
readOnce not inferred with an if guard

### ISSUE THREAD

**Issue by madgen** [camfort/camfort#53]
For the following loop we infer `stencil (reflexive(dim=1)) :: q`:

```fortran
do i = 1, 10
  if(.true.) q(i) = -q(i)
end do
```

When the if guard is removed, however, we infer `stencil readOnce, (reflexive(dim=1)) :: q`:

```fortran
do i = 1, 10
  q(i) = -q(i)
end do
```

**Comment by dorchard** [comment]
This is actually due to 'if' statements because the LHS and RHS subscript both count as RHS expressions.

**Comment by madgen** [comment]
You don't mean this is intentional, do you?

**Comment by dorchard** [comment]
No, just pointing out where/why the bug occurs

**Comment by dorchard** [comment]
The bug is actually in fortran-src in the blockRhsExprs. There is a lack of granularity there over what counts as an Rhs.
