### ISSUE TITLE
Unusual non-local interactions between subroutines for stencils

### ISSUE THREAD

**Issue by dorchard** [camfort/camfort#54]
Take the following code:
```
module tmp
  implicit none

  contains

    subroutine five()
      real u(0:10, 0:10)
      integer :: i, j
      real    :: a, b

      do i = 1, 10
        do j = 1, 10
           b = u(i, j-1) + u(i, j+1)
           a = u(i+1, j) + u(i-1,j)
           u(i,j) = u(i,j) + a + b
        end do
    end do

   end subroutine 

   ! comment this out to change the stencil on line 15
   subroutine blank()
     integer mustBeHere
   end subroutine

   
end module tmp
```
If you run stencils-infer on this you get:
```
$ camfort stencils-infer tmp.f90
Infering stencil specs for 'tmp.f90'
tmp.f90
(15:12)-(15:34)    stencil (centered(depth=1, dim=2)) :: u
```
But this is only a sub-specification of what should be inferred. Now comment out the "blank" subroutine. We now get:
```
(15:12)-(15:34)    stencil readOnce, (reflexive(dim=1))*(centered(depth=1, dim=2)) + (reflexive(dim=2))*(centered(depth=1, dim=1)) :: u
```

This sounds like it is something coming from fortran-src then?

**Comment by dorchard** [comment]
The plot thickens: if you change this from a `module` to a `program` then regardless of whether the "blank" subroutine is present or not inference gives:
```
(15:12)-(15:34)    stencil (centered(depth=1, dim=2)) :: u
(15:12)-(15:34)    stencil (centered(depth=1, dim=2)) :: u
```
This makes me think it is something to do with the blocks analysis interacting strangely with flows analysis?

**Comment by mrd** [comment]
fixed by https://github.com/camfort/fortran-src/commit/420bc6b1c591f82d262015ff74c95f13ff8704be

**Comment by madgen** [comment]
@mrd could you rerun the evaluation when you have time?
