### ISSUE TITLE
Multiplicity modifier should come before approximation modifier

### ISSUE THREAD

**Issue by madgen** [camfort/camfort#55]
Currently for

```fortran
program example
  integer, dimension(10) :: q
  integer :: i

  do i = 1, 10
    q(i) = q(i) + q(i+4)
  end do
end program example
```

we infer

```
(6:5)-(6:24)    stencil atLeast, readOnce, (reflexive(dim=1)) :: q
(6:5)-(6:24)    stencil atMost, readOnce, (forward(depth=4, dim=1)) + (reflexive(dim=1)) :: q
```

According to our latest decisions on the design multiplicity modifier should be the outermost modifier to be consistent with how we generate denotational model from the specification.

**Comment by GuiltyDolphin** [comment]
This is current behavior as of https://github.com/camfort/camfort/commit/750ea529562db24fe8b12faa8e4115cf83f23015
