### ISSUE TITLE
Fails on `ASSOCIATE` statement (?)

### ISSUE THREAD

**Issue by msleigh** [camfort/camfort#58]
CamFort (0.902) fails on `ASSOCIATE` statement, e.g.:

    ASSOCIATE(YDVAB=>YDGEOMETRY%YRVAB,YDVETA=>YDGEOMETRY%YRVETA,YDVFE=>YDGEOMETRY%YRVFE,YDSTA=>YDGEOMETRY%YRSTA, &

with error:

    $ camfort stencils-check example.F90 --debug
    
    Checking stencil specs for 'example.F90'
    camfort: fortran-src: user error (79:1: example.F90: lexing failed. Last parsed token: TNewline (78:1)-(78:1).)

**Comment by madgen** [comment]
This is an issue with the parsing dependency https://github.com/camfort/fortran-src. It supports up to Fortran 90 and some Fortran 95. We are working on fully supporting 95 and then, hopefully, will take a stab at Fortran 2003 which has `ASSOCIATE` statements.

**Comment by dorchard** [comment]
This feature has (finally) almost been implemented: see PR here: https://github.com/camfort/fortran-src/pull/165
Should be done soon and merged in.

**Comment by raehik** [comment]
Snippet provided (without continuation) parses fine with recent merge. `ASSOCIATE` blocks are (currently) restricted to the Fortran 2003 parser, so you'll want to call

    fortran-src -v Fortran2003 $FILE.f90

or

    fortran-src $FILE.f2003

I can imagine some possible issues still depending on how CamFort calls fortran-src (do we get to specify the Fortran parser to use), but I think that deserves a seperate issue. Closing!
