### ISSUE TITLE
`stencils-synth` reinserts existing stencil specification

### ISSUE THREAD

**Issue by vimuel** [camfort/camfort#63]
**Observed behaviour**  
`stencils-synth` currently reinserts existing stencil specifications, leading to replication.

**Desired behaviour**  
`stencils-synth` should leave existing correct specifications and complain about existing wrong specifications.

**Comment by GuiltyDolphin** [comment]
See also #62.

**Comment by GuiltyDolphin** [comment]
@vimuel Could you check that CamFort has the desired behavior now?
