### ISSUE TITLE
Automatically install tab-completion

### ISSUE THREAD

**Issue by GuiltyDolphin** [camfort/camfort#73]
Currently, users are required to do something along the lines of `source <(camfort --bash-completion-script=$(which camfort)` to get tab-completion for `camfort` working (in that particular shell).

We should either:

* Install completion script automatically (preferred)
* Provide the completion script for users to install manually

**Comment by GuiltyDolphin** [comment]
We now provide information in the readme that indicates how users can add tab completion. Good enough @dorchard? I'm not sure if we can automatically install it without either root or getting users to jump through other hoops.

**Comment by dorchard** [comment]
That sounds fine to me.

**Comment by GuiltyDolphin** [comment]
In that case, implemented in https://github.com/camfort/camfort/commit/7c56f5eedcb7d726c6dbfc244c9d95d8128cf4d8.
