### ISSUE TITLE
Instantiation of unit polymorphic functions is broken. 

### ISSUE THREAD

**Issue by dorchard** [camfort/camfort#8]
See the example:
https://github.com/dorchard/camfort/blob/master/samples/units/poly-scale.f90
which has polymorphic usage of the `dub` function:

     real function dub(x) 
        real x
        real :: k = 2
        dub = k*x
     end function

This should be fine. But, 'dub' does not type check. If you substitute in the value of k (i.e. constant propagate/beta reduce) to 

      real function dub(x) 
          real x
          dub = 2*x
      end function

Then it is fine. But as a variable it fails.

**Comment by dorchard** [comment]
I believe this is a bug in the instantiator which is in "addInterproceduralConstraints" in Extension.Units. It pops out at 'handleArgPair' (a subfunction of addInterproceduralConstarints') where polymorphic instantiation copies and instantiates a single row which gives the constraint between inputs and outputs [this is not the source of the error, but just where we see it manifest]. But there may be other constraints put in place on  other variables in the matrix which are not part of this row. Thus, when only this row is copied, there becomes a disconnect between  other constraints on variables in the function. I think we need to copy a larger chunk then: probably by copying and instantiating that "header" constraint and any other 'related' constraints (i.e. all other rows which have non-zero elements in columns for the arguments or return value of that function).

**Comment by dorchard** [comment]
This is fixed in @mrd's branch `new-units`

**Comment by madgen** [comment]
Let's wait until it gets back to the master branch to close it.

**Comment by dorchard** [comment]
This is now fixed in the master.
