### ISSUE TITLE
stencils-check displaying blank inference for some stencils

### ISSUE THREAD

**Issue by GuiltyDolphin** [camfort/camfort#83]
With the following file (`failing.f90`):

```fortran
program failing
  integer :: i
  real, dimension(10) :: a, b
  do i = 1, 10
     != stencil forward(depth=1, dim=1) :: a
     b(1) = a(1)
  end do
end program
```

Running `camfort stencils-check failing.f90` yields:

```
Checking stencil specs for 'failing.f90'

failing.f90
(5:6)-(5:44)    Not well specified.
        Specification is:
                stencil (forward(depth=1, dim=1)) :: a

        but at (6:6)-(6:16) the code behaves as
                
```

Which to me implies we shouldn't be inferring a stencil here (@dorchard is that correct?) in which case we should probably have a nicer error message (e.g., `But no stencil should be present`).

**Comment by madgen** [comment]
@dorchard bump

**Comment by GuiltyDolphin** [comment]
@madgen What do you suggest instead? I don't think we should just ignore it, as the user has clearly attempted to put a specification in (or maybe an older version of the software has erroneously inserted one). Some form of warning/error would seem appropriate to me.

**Comment by madgen** [comment]
As I said, warning or error.
