### ISSUE TITLE
stencils-check accepting duplicate stencils

### ISSUE THREAD

**Issue by GuiltyDolphin** [camfort/camfort#89]
For example, with the file (`example.f90`):

```fortran
program example
  integer :: i
  real, dimension(10) :: a, b
  do i = 1, 10
     != stencil readOnce, (forward(depth=1, dim=1, nonpointed)) :: a
     != stencil readOnce, (forward(depth=1, dim=1, nonpointed)) :: a
     b(i) = a(i+1)
  end do
end program
```

Running `camfort stencils-check example.f90` we get:

```
Checking stencil specs for 'example.f90'

example.f90
(5:6)-(5:68)    Correct.
(6:6)-(6:68)    Correct.
```

Which is accepting both stencils, even though they are the same. We should warn the user that they have a duplicate stencil.

**Comment by dorchard** [comment]
Yes I think a warning here is fine. Good spot.

**Comment by GuiltyDolphin** [comment]
@dorchard Would you want us to automatically clean this up in synthesis? Abort synthesis, or just continue, ignoring it?

**Comment by dorchard** [comment]
I think just continue but with a warning (if both are correct).
