### ISSUE TITLE
Cross-module type declarations not accounted for in stencil inference

### ISSUE THREAD

**Issue by dorchard** [camfort/camfort#98]
Example:
foo.f90
```fortran
program foo
  implicit integer (i)
  use foo2
  real :: x

  do i = 1, 10
     a(i) = a(i)
  end do

end program foo
```
and foo2.f90 (a module)
```fortran
module foo2
  real, dimension(10) :: a
end module
```
No specification is inferred here. Looking at the code, we need to convert `doAnalysisSummary` (and all other input functions) to work with mod files.

**Comment by GuiltyDolphin** [comment]
Fixed as of b981ba89cf3bd3bfb4ce6a4d5c89678c7face63d.
